query1="SELECT SCHEMA_NAME, COUNT(*) FROM information_schema.TABLES GROUP BY SCHEMA_NAME ORDER BY SCHEMA_NAME";
query2="SELECT SCHEMA_NAME, COUNT(*) FROM information_schema.COLUMNS GROUP BY SCHEMA_NAME ORDER BY SCHEMA_NAME";

